spring.application.name=micro-chat-user-service
security.secret-key=${SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
security.jwt-expiration=${JWT_EXPIRATION:1440000}
security.refresh-expiration=${REFRESH_EXPIRATION:604800000}

spring.datasource.url=jdbc:postgresql://${HOST:localhost}:${PORT:5432}/${DB_NAME:quiz}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:our-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.url=http://localhost:4200